rust:
  - backend-end/**
  - "**"
typescript:
  - front-end/**
  - "**"
# code:
#   - "src/**"
#   - "TAG"
#   - Dockerfile
#   - "tests/**"
#   - ".github/**"
#   - "*.toml"
#   - Cargo.lock
#   - "package.json"
#   - "package-lock.json"
#   - ".codeclimate.yml"
