[package]
name = "logscreen"
# don't change this, it's updated before an actual build by update-version.sh
version = "0.0.0-development"
edition = "2021"
rust-version = "1.81.0"
authors = ["Kristof Mattei"]
description = "logscreen in Rust"
license-file = "LICENSE"
categories = ["fun"]
keywords = ["random"]
repository = "https://github.com/kristof-mattei/logscreen"

[[bin]]
name = "logscreen"
path = "back-end/src/main.rs"

[lints.clippy]
# don't stop from compiling / running
all = "warn"
pedantic = "warn"
cargo = "warn"
# this one causes confusion when combining variables (`foo`) and
# dereferenced variables (`foo.bar`). The latter cannot be inlined
# so we don't inline anything
uninlined-format-args = { level = "allow", priority = 127 }

[lints.rust]
let_underscore_drop = { level = "deny", priority = 127 }
non_ascii_idents = { level = "deny", priority = 127 }

[profile.dev.package.backtrace]
opt-level = 3

[[test]]
name = "logscreen"
path = "back-end/tests/integration_tests.rs"

[features]
coverage = []

[dependencies]
axum = { version = "0.7.5" }
color-eyre = { git = "https://github.com/eyre-rs/eyre", rev = "2dc0688d33a487009e8bc3222cbab135261383b0", features = [
    "track-caller",
] }
tokio = { version = "1.40.0", features = [
    "macros",
    "io-util",
    "io-std",
    "rt-multi-thread",
    "signal",
    "time",
] }
tokio-util = "0.7.12"
tower = "0.5.0"
tower-http = { version = "0.5.2", features = ["cors", "fs", "trace"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing-error = "0.2.0"
url = { version = "2.5.2", features = ["serde"] }
socketioxide = { version = "0.14.1", features = ["tracing"] }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.128"
backtrace = "0.3.73"
reverse-proxy-service = { git = "https://github.com/manorom/reverse-proxy-service", rev = "fda8bf28b4c602bdcf5f941b584e3e4940a1491e", features = [
    "axum",
] }
# console-subscriber = "0.2.0"
# dotenvy = "0.15.7"
# axum-csp = "0.0.7"
# thiserror = "1.0.37"

# [dev-dependencies]
# stubr = "0.6.2"

# We compile the Docker container with musl to get a static library. Smaller, faster.
# BUT that means that we need to include openssl
# Documentation on the syntax:
# https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies
[target.'cfg(all(target_arch = "x86_64", target_os="linux", target_env="musl"))'.dependencies]
openssl = { version = "0.10.66", features = ["vendored"] }
